name: Release WebExtension

on:
  push:
    tags: ["webext-v*"]

permissions:
  contents: write

jobs:
  release:
    uses: kud/webext/.github/workflows/release-extension.yml@main
    with:
      root: webext
      ignore-files: publish.sh amo amo/**
      icon: assets/icons/foxhop-128.png
    secrets: inherit
